public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int a = 100000;
        byte c = 10;
        short d = 1000;
        long e = 9000000L;
        float f = 4.25f;
        double g = 5.54678;
        System.out.println("Значение переменной a с типом int равно " + a);
        System.out.println("Значение переменной с с типом byte равно " + c);
        System.out.println("Значение переменной d с типом short ранво " + d);
        System.out.println("Значение переменной e с типом  long равно " + e);
        System.out.println("Значение переменной f c с типом float равно " + f);
        System.out.println("Значение переменной g с типом double равно " + g);
        System.out.println("Задача 2");
        float aa = 27.12f;
        long bb = 987678965549L;
        double cc = 2.786;
        short dd = 569;
        short ee = -159;
        short ff = 27897;
        byte gg = 67;
        System.out.println(aa);
        System.out.println(bb);
        System.out.println(cc);
        System.out.println(dd);
        System.out.println(ee);
        System.out.println(ff);
        System.out.println(gg);
        System.out.println("Задача 3");
        byte classA = 23;
        byte classB = 27;
        byte classC = 30;
        short paper = 480;
        int classD = classA + classB + classC;
        int result = paper / classD;
        System.out.println("На каждого ученика рассчитано " + result + " листов бумаги");
        System.out.println("Задача 4");
        int but = 16;
        but = but / 2;
        int butOne = but * 20;
        System.out.println("За 20 минут машина произвела " + butOne + " штук бутылок");
        int butTwo = (but * 60) * 24;
        System.out.println("За сутки машина произвела " + butTwo + " штук бутылок");
        int butThree = butTwo * 3;
        System.out.println("За 3 дня машина произвела " + butThree + " штук бутылок");
        int butFor = butTwo * 30;
        System.out.println("За месяц машина произвела " + butFor + " штук бутылок");
        System.out.println("Задача 5");
        int vsego = 120;
        int w = 2;
        int b = 4;
        int wB = w + b;
        int classVsego = vsego / wB;
        int bel = classVsego * b;
        int kor = classVsego * w;
        System.out.println("В школе, где " + classVsego + " классов, нужно " + bel + " банок белой краски и " + kor + " банок коричневой краски");
        System.out.println("Задача 6");
        int banan = 5 * 80;
        int milk = 105 * 2;
        int froz = 2 * 100;
        int egg = 4 * 70;
        int vsegoGr = banan + milk + froz + egg;
        System.out.println("Вес спортзавтрака равен " + vsegoGr + " грамм");
        float vsegoKg = vsegoGr / 1000f;
        System.out.println("Вес завтрака в кг равен " + vsegoKg + " кг");
        System.out.println("Задача 7");
        int ves = 7;
        int vesGr = 7 * 1000;
        int OneD = vesGr / 250;
        int TwoD = vesGr / 500;
        System.out.println("Если спортсмен каждый день будет худеть на 250 грамм - то у него уйдет " + OneD + " дней");
        System.out.println("Если спортсмен будет терять каждый день по 500 грамм - то у него уйдет " + TwoD + " дней");
        System.out.println("Задача 8");
        int Masha = 67760;
        int Denis = 83690;
        int Kris = 76230;
        int MashaProc = (Masha * 10) / 100;
        int MashaZp = Masha + MashaProc;
        int MashaOne = Masha * 12;
        int MashaTwo = (MashaZp * 12) - MashaOne;
        System.out.println("Маша теперь получает " + MashaZp + " рублей." + " Годовой доход вырос на " + MashaTwo + " рублей.");
        int DenisProc = (Denis * 10) / 100;
        int DenisZp = Denis + DenisProc;
        int DenisOne = Denis * 12;
        int DenisTwo = (DenisZp * 12) - DenisOne;
        System.out.println("Денис теперь получает " + DenisZp + " рублей." + " Годовой доход вырос на " + DenisTwo + " рублей.");
        int krisProc = (76230 * 10) / 100;
        int KrisZp =  Kris + krisProc;
        int KrisOne = Kris * 12;
        int KrisTwo = (KrisZp * 12) - KrisOne;
        System.out.println("Кристина теперь получает " + KrisZp + " рублей. Годовой доход вырос на " + KrisTwo + " рублей");

    }
}